from pathlib import Path
import io
import os

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st
from dotenv import load_dotenv

from src.evidence_nlp import (
    build_intelligence,
    congress_number,
    evidence_context,
    inspect_export,
    merge_v10_exports,
    split_evidence,
    theme_by_congress,
    theme_counts,
    top_evidence_phrases,
)


load_dotenv()
BASE = Path(__file__).resolve().parent
DATA_DIR = BASE / "data"

st.set_page_config(
    page_title="DAQO China Strategic Exposure Intelligence",
    page_icon="📡",
    layout="wide",
)

st.markdown(
    """
    <style>
    .block-container {max-width: 1550px; padding-top: 1.2rem; padding-bottom: 3rem;}
    [data-testid="stMetric"] {
        border: 1px solid rgba(49, 88, 120, .25);
        padding: 13px;
        border-radius: 13px;
        background: rgba(30, 55, 80, .035);
    }
    .evidence-card {
        padding: 14px;
        border-radius: 12px;
        border: 1px solid #d7dee7;
        margin-bottom: 10px;
        background: #fafcff;
    }
    </style>
    """,
    unsafe_allow_html=True,
)

st.title("📡 DAQO — China Strategic Exposure Intelligence")
st.caption(
    "Evidence-first NLP analysis built for the Excel exports produced by the simplified DAQO RAG V10 workflow."
)

with st.expander("🧠 How this dashboard works", expanded=False):
    st.markdown(
        """
        This app accepts **one or many DAQO RAG V10 Excel exports**. Each file must contain
        the same V10 workbook structure, including **All Results** and **Evidence** sheets.

        The files are merged into one research dataset. NLP is applied primarily to the
        **Evidence Quote** and **Why It Matters** text. The China Exclusion Index is a
        transparent screening indicator, not a forecast that a bill will become law.
        """
    )

st.subheader("📂 Analysis data")
st.caption("Recommended: upload the newest Excel exports generated by the DAQO RAG V10 app. You may upload one file or many files together.")

packaged = sorted(
    [p for p in DATA_DIR.glob("*.xlsx") if p.stem.isdigit()],
    key=lambda p: int(p.stem),
)
mode_options = ["Upload V10 RAG exports"]
if packaged:
    mode_options.append("Use packaged V10 RAG exports")

mode = st.radio(
    "Data input",
    mode_options,
    horizontal=True,
)

sources = []

if mode == "Use packaged V10 RAG exports":
    for path in packaged:
        sources.append((path.name, path.read_bytes()))
    st.caption("Packaged files: " + ", ".join(path.name for path in packaged))
else:
    uploads = st.file_uploader(
        "Upload one or more DAQO RAG V10 Excel files",
        type=["xlsx"],
        accept_multiple_files=True,
        help=(
            "You can upload a single completed RAG export or multiple exports. "
            "The app merges them automatically."
        ),
    )
    for uploaded in uploads or []:
        sources.append((uploaded.name, uploaded.getvalue()))

    if not sources:
        st.info(
            "Upload at least one V10 RAG Excel file. The workbook must contain "
            "the All Results and Evidence sheets."
        )
        st.stop()

quality = pd.DataFrame([inspect_export(name, blob) for name, blob in sources])

st.markdown("#### ✅ File validation")
st.dataframe(quality, use_container_width=True, hide_index=True)

ready_sources = [
    source
    for source, status in zip(sources, quality.to_dict("records"))
    if status["Status"] == "READY"
]

if not ready_sources:
    st.error("No valid V10 RAG exports were detected.")
    st.stop()

with st.spinner("Merging RAG exports and building the evidence NLP layer..."):
    actions, evidence, quality = merge_v10_exports(ready_sources)
    df = build_intelligence(actions)

if df.empty:
    st.error("The uploaded files did not contain usable All Results rows.")
    st.stop()

st.subheader("🔎 Filter Congressional data")
filter1, filter2 = st.columns(2)

congresses = sorted(
    [x for x in df["Congress"].dropna().unique() if str(x) != "Unknown"],
    key=congress_number,
)
countries = sorted(
    [x for x in df["Country"].dropna().unique() if str(x).strip()]
)

with filter1:
    st.markdown("#### 🏛️ Congress")
    selected_congress = st.multiselect(
        "Congress sessions to include",
        congresses,
        default=congresses,
    )

with filter2:
    st.markdown("#### 🌎 Country")
    selected_countries = st.multiselect(
        "Countries to include",
        countries,
        default=countries,
        help="Select China, Mexico, or multiple countries.",
    )

view = df.copy()
if selected_congress:
    view = view[view["Congress"].isin(selected_congress)]
else:
    view = view.iloc[0:0]

if selected_countries:
    view = view[view["Country"].isin(selected_countries)]
else:
    view = view.iloc[0:0]

success = view[
    view["Analysis Status"].fillna("").astype(str).str.upper() == "SUCCESS"
].copy()
relevant = success[
    success["Relevant"].fillna("").astype(str).str.upper() == "YES"
].copy()
failed = view[
    view["Analysis Status"].fillna("").astype(str).str.upper() == "FAILED"
].copy()

st.subheader("📊 Evidence overview")
avg_index = relevant["China Exclusion Index"].mean() if len(relevant) else 0
evidence_count = int(relevant["Evidence Count"].sum()) if len(relevant) else 0

k1, k2, k3, k4, k5 = st.columns(5)
k1.metric("Files loaded", len(ready_sources))
k2.metric("Actions in view", f"{len(view):,}")
k3.metric("Relevant actions", f"{len(relevant):,}")
k4.metric("Evidence extracts", f"{evidence_count:,}")
k5.metric("China Exclusion Index", f"{avg_index:.1f}/100")

if failed.empty:
    st.success("All actions in the current view have a completed analysis status.")
else:
    st.warning(
        f"{len(failed):,} action(s) are marked ANALYSIS FAILED and are excluded from relevance metrics."
    )

left, right = st.columns([1.55, 1])

with left:
    st.subheader("📈 China exclusion pressure by Congress")
    if relevant.empty:
        st.info("No relevant actions are available for the current filters.")
    else:
        trend = (
            relevant.groupby("Congress", as_index=False)
            .agg(
                Exclusion_Index=("China Exclusion Index", "mean"),
                Relevant_Actions=("Bill", "count"),
                Evidence=("Evidence Count", "sum"),
                High_Signals=(
                    "China Exclusion Index",
                    lambda values: int((values >= 70).sum()),
                ),
            )
        )
        trend["Order"] = trend["Congress"].apply(congress_number)
        trend = trend.sort_values("Order")

        fig = go.Figure()
        fig.add_trace(
            go.Scatter(
                x=trend["Congress"],
                y=trend["Exclusion_Index"],
                mode="lines+markers",
                name="Exclusion Index",
                line={"width": 4},
            )
        )
        fig.add_trace(
            go.Bar(
                x=trend["Congress"],
                y=trend["Relevant_Actions"],
                name="Relevant actions",
                opacity=0.28,
                yaxis="y2",
            )
        )
        fig.update_layout(
            height=390,
            margin=dict(l=10, r=10, t=25, b=10),
            yaxis=dict(title="Exclusion Index", range=[0, 100]),
            yaxis2=dict(
                title="Relevant actions",
                overlaying="y",
                side="right",
                showgrid=False,
            ),
            legend=dict(orientation="h", y=1.12),
        )
        st.plotly_chart(fig, use_container_width=True)

    st.subheader("🌎 Risk / opportunity mix by country")
    if not relevant.empty:
        mix = (
            relevant.groupby(["Country", "Primary Classification"])
            .size()
            .reset_index(name="Actions")
        )
        fig = px.bar(
            mix,
            x="Country",
            y="Actions",
            color="Primary Classification",
            barmode="stack",
            color_discrete_sequence=px.colors.qualitative.Bold,
        )
        fig.update_layout(
            height=390,
            margin=dict(l=10, r=10, t=10, b=10),
            legend_title_text="",
        )
        st.plotly_chart(fig, use_container_width=True)

with right:
    st.subheader("🧭 Evidence explorer")
    choices = relevant.sort_values(
        ["China Exclusion Index", "Evidence Strength", "Evidence Count"],
        ascending=False,
    )

    if choices.empty:
        st.info("No relevant evidence to show.")
    else:
        labels = choices.apply(
            lambda row: (
                f"{row['Bill']} | {row['Congress']} | "
                f"{row['Country']} | {row['China Exclusion Index']:.0f}/100"
            ),
            axis=1,
        ).tolist()

        selected = st.selectbox("Choose a Congressional action", labels)
        row = choices.iloc[labels.index(selected)]

        st.markdown(
            f"""
            <div class="evidence-card">
            <b>{row['Bill']} — {row['Title']}</b><br>
            Congress: {row['Congress']}<br>
            Country: {row['Country']}<br>
            Classification: {row['Primary Classification']}<br>
            Exclusion Index: <b>{row['China Exclusion Index']:.0f}/100</b><br>
            Evidence strength: {row['Evidence Strength']:.0f}/100<br>
            Evidence extracts: {int(row['Evidence Count'])}
            </div>
            """,
            unsafe_allow_html=True,
        )

        st.write("**NLP themes detected**")
        st.write(row.get("NLP Themes", "") or "No restrictive-China theme matched.")

        quotes = split_evidence(row.get("Evidence Quotes"))
        whys = split_evidence(row.get("Evidence Why It Matters"))

        for i, quote in enumerate(quotes[:6]):
            why = whys[i] if i < len(whys) else ""
            st.info(
                f"Evidence {i + 1}: {quote}\n\n"
                f"Why it matters: {why}"
            )

        url = str(row.get("Source URL", ""))
        if url and url.lower() != "nan":
            st.link_button("🔗 Open Congressional source", url)

st.divider()
c1, c2 = st.columns(2)

with c1:
    st.subheader("🔥 Restrictive-China policy mechanisms")
    themes = theme_counts(relevant)
    if themes.empty:
        st.info("No policy themes detected under the current filters.")
    else:
        fig = px.bar(
            themes.sort_values("Actions"),
            x="Actions",
            y="Theme",
            orientation="h",
            color="Actions",
        )
        fig.update_layout(
            height=420,
            margin=dict(l=10, r=10, t=10, b=10),
            coloraxis_showscale=False,
        )
        st.plotly_chart(fig, use_container_width=True)

with c2:
    st.subheader("🧩 Policy mechanism heatmap")
    heat = theme_by_congress(relevant)
    if heat.empty:
        st.info("No policy mechanism data to display.")
    else:
        pivot = heat.pivot(
            index="Theme",
            columns="Congress",
            values="Actions",
        ).fillna(0)
        pivot = pivot[sorted(pivot.columns, key=congress_number)]
        fig = px.imshow(
            pivot,
            aspect="auto",
            text_auto=True,
            labels={
                "x": "Congress",
                "y": "Policy mechanism",
                "color": "Actions",
            },
        )
        fig.update_layout(height=420, margin=dict(l=5, r=5, t=5, b=5))
        st.plotly_chart(fig, use_container_width=True)

st.divider()
c3, c4 = st.columns(2)

with c3:
    st.subheader("☁️ Evidence language landscape")
    phrases = top_evidence_phrases(relevant, 30)
    if phrases.empty:
        st.info("Not enough evidence text for TF-IDF phrase analysis.")
    else:
        phrases["Group"] = "Evidence phrases"
        fig = px.treemap(
            phrases,
            path=["Group", "Phrase"],
            values="Importance",
            color="Importance",
        )
        fig.update_layout(
            height=410,
            margin=dict(l=5, r=5, t=5, b=5),
            coloraxis_showscale=False,
        )
        st.plotly_chart(fig, use_container_width=True)

with c4:
    st.subheader("🎯 Exclusion signal distribution")
    band_order = ["High", "Elevated", "Watch", "Low"]
    distribution = (
        relevant["Exclusion Band"]
        .value_counts()
        .reindex(band_order, fill_value=0)
        .reset_index()
    )
    distribution.columns = ["Signal", "Actions"]
    fig = px.bar(
        distribution,
        x="Signal",
        y="Actions",
        color="Signal",
        color_discrete_map={
            "High": "#dc2626",
            "Elevated": "#f59e0b",
            "Watch": "#3b82f6",
            "Low": "#16a34a",
        },
    )
    fig.update_layout(
        height=410,
        margin=dict(l=5, r=5, t=5, b=5),
        showlegend=False,
    )
    st.plotly_chart(fig, use_container_width=True)

st.divider()
st.subheader("✨ OpenAI Evidence Brief")

api_key = os.getenv("OPENAI_API_KEY", "").strip()
if not api_key:
    try:
        api_key = str(st.secrets.get("OPENAI_API_KEY", "")).strip()
    except Exception:
        api_key = ""

a1, a2 = st.columns(2)
model = a1.selectbox(
    "OpenAI model",
    ["gpt-5.4-mini", "gpt-5.4-nano"],
    index=0,
)
max_actions = a2.slider(
    "Evidence-rich actions sent to OpenAI",
    min_value=5,
    max_value=20,
    value=12,
)

question = st.text_area(
    "Research question",
    value=(
        "Based only on the selected Congressional evidence, is U.S. policy "
        "increasingly excluding or reducing dependence on China, and what are "
        "the implications for DAQO's China-export, Mexico-manufacture and "
        "U.S.-manufacture strategies?"
    ),
    height=105,
)

if not api_key:
    st.caption(
        "Add OPENAI_API_KEY to .env locally or to Streamlit Secrets to enable this section."
    )

if st.button(
    "🧠 Generate evidence brief",
    type="primary",
    disabled=not bool(api_key) or relevant.empty,
):
    from openai import OpenAI

    context = evidence_context(relevant, max_actions=max_actions)

    prompt = f"""
You are a policy research analyst studying DAQO's strategic approach to serving the U.S. market.

Answer the research question using ONLY the evidence provided below.

RESEARCH QUESTION:
{question}

RULES:
- Do not invent facts outside the supplied Congressional evidence.
- Distinguish evidence from interpretation.
- Cite the bill number for every major finding.
- Identify recurring policy mechanisms and changes across Congresses.
- Explain implications for CHINA-EXPORT, MEXICO-MANUFACTURE, and US-MANUFACTURE only when supported.
- Mention uncertainty, failed analysis, or weak evidence when relevant.
- Provide: Executive Summary, Key Evidence Patterns, Strategic Implications, and Evidence Strength.

EVIDENCE:
{context}
"""

    try:
        client = OpenAI(api_key=api_key)
        response = client.responses.create(
            model=model,
            input=prompt,
            max_output_tokens=1400,
        )
        st.markdown(response.output_text)
    except Exception as exc:
        st.error(f"OpenAI analysis failed: {exc}")

st.divider()
st.subheader("📋 Evidence-backed intelligence table")

table_cols = [
    "Bill", "Title", "Congress", "Country", "Analysis Status", "Relevant",
    "Primary Classification", "Policy Stage", "Directness",
    "China Exclusion Index", "Exclusion Band", "Evidence Strength",
    "Evidence Count", "NLP Themes", "Matched Evidence Terms", "Source URL",
    "Source File",
]

st.dataframe(
    view[[c for c in table_cols if c in view.columns]]
    .sort_values(
        ["China Exclusion Index", "Evidence Strength"],
        ascending=False,
    ),
    use_container_width=True,
    hide_index=True,
)

st.subheader("📥 Export merged NLP research")

buffer = io.BytesIO()
with pd.ExcelWriter(buffer, engine="openpyxl") as writer:
    view.to_excel(writer, index=False, sheet_name="Merged Actions")
    evidence.to_excel(writer, index=False, sheet_name="Merged Evidence")
    theme_counts(relevant).to_excel(writer, index=False, sheet_name="Policy Themes")
    top_evidence_phrases(relevant, 50).to_excel(
        writer,
        index=False,
        sheet_name="NLP Phrases",
    )
    quality.to_excel(writer, index=False, sheet_name="Data Quality")

    for ws in writer.book.worksheets:
        ws.freeze_panes = "A2"
        ws.auto_filter.ref = ws.dimensions
        for column in ws.columns:
            letter = column[0].column_letter
            width = 12
            for cell in list(column)[:100]:
                width = max(width, min(len(str(cell.value or "")) + 2, 60))
            ws.column_dimensions[letter].width = width

st.download_button(
    "⬇️ Download merged DAQO NLP intelligence",
    data=buffer.getvalue(),
    file_name="DAQO_Merged_China_Exposure_Intelligence.xlsx",
    mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
)
